//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Softwares = new HashSet<Softwares>();
        }
    
        public int employee_id { get; set; }
        public string employee_name { get; set; }
        public string employee_surname { get; set; }
        public int employee_gender { get; set; }
        public int employee_salary { get; set; }
        public int employee_department { get; set; }
        public System.DateTime employee_start_date { get; set; }
        public int employee_coid { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Department Department { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Softwares> Softwares { get; set; }
    }
}
