//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup
    {
        public int setup_id { get; set; }
        public System.DateTime setup_date { get; set; }
        public int setup_product { get; set; }
        public int setup_costumer { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
